### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by indutny** [indutny/mini-test.c#1]
`mini_run_single` should be implemented for Windows. Implementation may be a reduced copy of one in libuv's test runner.

**Comment by indutny** [comment]
Here is the link to [libuv's implementation][0] just in case. Note that we don't need most of it, and the `wait` and `start` methods should be merged into one.

[0]: https://github.com/libuv/libuv/blob/12f18159cf2f40fe12c62eb7a0ae22b6dd5548d5/test/runner-win.c#L69-L200

**Comment by indutny** [comment]
cc @refack Not sure if you are interested, but adding you to the thread just in case. :wink:

**Comment by refack** [comment]
I'm in obv.
But what's the goal? "Minimalistic test suite for C projects"? a test runner a la `tap`/`mocha`?
Or actual tests of something?

**Comment by indutny** [comment]
First one, this is very minimal `tap`/`mocha` thing, but for C projects.

**Comment by refack** [comment]
On it. `libuv` is a good starting point 👍
